const { client } = require('./connections.js');

const SQL = `
CREATE TABLE IF NOT EXISTS users (
    userId INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(30) NOT NULL,
    firstname VARCHAR(30) NOT NULL,
    lastname VARCHAR(30) NOT NULL,
    ismember BOOLEAN NOT NULL DEFAULT FALSE,
    isAdmin BOOLEAN NOT NULL DEFAULT FALSE,
    hash varchar(60) NOT NULL
    
);

CREATE TABLE IF NOT EXISTS messages (
    messageID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userID INTEGER NULL REFERENCES users(userID) ON DELETE SET NULL,
    title VARCHAR(100) NOT NULL,
    message VARCHAR(200) NOT NULL,
    created TIMESTAMP WITH TIME ZONE
);
`

async function main(){

    await client.connect();
    await client.query(SQL);
    await client.end();
    console.log('The database tables have been recreated.');

}

main();